### ISSUE TITLE
Unexpected TS files in the published library

### ISSUE THREAD

**Issue by quantang** [garronej/run_exclusive#4]
Hello,

I found that this published code contains the source code of the TS file, which will bring trouble when it is imported by other packages. Ideally, the published library should only contain JS file and the D.TS files.

Could you exclude the source TS file from the published library?

Cheers.

**Comment by garronej** [comment]
Hi thanks for submitting,

I am aware of the trouble including `.ts` files could bring and I took care to mitigate as much as possible the risk of issues.
Including them has advantages as well.  I have documented this [here](https://github.com/garronej/ts_ci/blob/develop/README.md#enabling-go-to-definition-to-redirect-to-the-source-ts-file).  
If you can give me an example where the `.ts` may causes problems I will remove them.  

Best regards,

**Comment by quantang** [comment]
Hi Garrone,

Thanks for your reply.

Generally, our project excludes the TS files from the node_modules, as it should not be necessary to transpile the published library again, which would some kind of wasting time and slow down the build process. However, as your project uses the TS file as the "type" attribute in the package.json, it will make the TS module resolution try to find it and eventually failed, as they are excluded by default.

Cheers.

**Comment by garronej** [comment]
@quantang, well it is a good enough reason for me to not include them anymore if it is troublesome in your case.
But just can you clarify, when you say that you exclude the TS files you mean via the `tsconfig.json`?
And are you using `run-exclusive` directly or as a dependency of [EVT](https://evt.land) or [denoify](https://github.com/garronej/denoify)?  

Best regards :octocat:

**Comment by garronej** [comment]
@quantang done in latest release.
